spring:
  http.multipart:
    max-file-size: 200MB
    max-request-size: 200MB
  datasource:
#   测试数据库
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username:
    password:
    driver-class: org.h2.Driver

#   druid数据源配置
    initial-size: 5
    max-active: 100
    min-idle: 1
    max-wait: 60000
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
    validation-query: select 1
    validation-query-timeout: 1
    test-on-borrow: true
    test-on-return: true
    test-while-idle: true
    time-between-eviction-runs-millis: 10000
    min-evictable-idle-time-millis: 30001
    async-close-connection-enable: true

logging:
  level:
    ROOT: INFO
    org.springframework: INFO