spring:
  profiles:
    active: dev
    http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true

server:
  tomcat:
    uri-encoding: UTF-8
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.ti.zbus_manager.mapper
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl